################ English language ##################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
title = "KaiLab"

################ Kurdish language ##################
[ku]
languageName = "کوردی"
languageCode = "ku"
contentDir = "content/kurdish"
weight = 2
title = "كايلاب"
description = "کایلاب - تاقیگەی زیرەکی دەستکردی کوردی"

