############# Kurdish navigation ##############

# main menu
[[main]]
name = "سەرەکی"
url = "/"
weight = 1

[[main]]
name = "پڕۆژەکان"
url = "/projects"
weight = 2

[[main]]
name = "بلۆگ"
url = "/blog"
weight = 3

[[main]]
name = "دەربارە"
url = "/about"
weight = 4


# footer menu
[[footer]]
name = "دەربارە"
url = "/about"
weight = 1

[[footer]]
name = "پەیوەندی"
url = "/contact"
weight = 2

[[footer]]
name = "سیاسەتی تایبەتمەندی"
url = "/privacy-policy"
weight = 3 