######################## Default configuration ####################
# Project site URL (include the /kailab/ path and a trailing slash)
baseURL = "https://polla.dev/kailab/"
title = "Hugoplate"
theme = "hugoplate"

# Ensure CSS/JS and links resolve correctly when the site lives under /kailab/
canonifyURLs = true
# (Do NOT set relativeURLs here; it can cause doubled subpaths on project sites)

# Local time zone
timeZone = "Asia/Baghdad"

# Language settings
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false
disableLanguages = []   # e.g., ["fr"] to disable French

# Post excerpts
summaryLength = 10

############################# Services #############################
[services]
  [services.googleAnalytics]
  ID = "G-MEASUREMENT_ID"  # replace with your GA4 ID or leave empty

  [services.disqus]
  shortname = "themefisher-template"  # replace/remove if not used

############################ Permalinks ############################
# Map sections explicitly as needed (example for a "pages" section):
[permalinks]
  pages = "/:slug/"

############################ Pagination ############################
[pagination]
disableAliases = false
pagerSize = 10
path = "page"

############################## Build ###############################
[build]
  [build.buildStats]
  enable = true

  # Cache-busting rule used by Hugoplate for the stats file
  [[build.cachebusters]]
  source = 'assets/notwatching/hugo_stats\.json'
  target = 'css'

############################# Modules ##############################
[module]
  # Mount the assets directory
  [[module.mounts]]
  source = "assets"
  target = "assets"

  # Mount the hugo_stats.json into a non-watched assets path
  [[module.mounts]]
  disableWatch = true
  source = "hugo_stats.json"
  target = "assets/notwatching/hugo_stats.json"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "WebAppManifest", "SearchIndex"]

############################# Imaging ##############################
[imaging]
quality = 80
resampleFilter = "Lanczos"

############################# Caches ###############################
[caches]
  [caches.images]
  dir = ":resourceDir/_gen"
  maxAge = "720h"

  [caches.assets]
  dir = ":resourceDir/_gen"
  maxAge = "720h"

############################# Markup ###############################
[markup]
  [markup.goldmark.renderer]
  unsafe = true

  [markup.highlight]
  style = "monokai"         # see https://xyproto.github.io/splash/docs/all.html
  lineNumbersInTable = false

  [markup.tableOfContents]
  startLevel = 2
  endLevel = 5
  ordered = true

############################ Media types ###########################
[mediaTypes]
  [mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

########################### Output Formats #########################
[outputFormats]
  [outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

  [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

############################# Plugins ##############################
# Hugoplate plugin assets expected under /plugins and /js

# CSS Plugins
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
lazy = true

[[params.plugins.css]]
link = "plugins/glightbox/glightbox.css"
lazy = true

[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
lazy = true

[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
lazy = true

[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"
lazy = true

# JS Plugins
[[params.plugins.js]]
link = "js/search.js"
lazy = false

[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
lazy = false

[[params.plugins.js]]
link = "plugins/cookie.js"
lazy = false

[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
lazy = true

[[params.plugins.js]]
link = "js/gallery-slider.js"
lazy = true

[[params.plugins.js]]
link = "js/accordion.js"
lazy = true

[[params.plugins.js]]
link = "js/tab.js"
lazy = true

[[params.plugins.js]]
link = "js/modal.js"
lazy = true

[[params.plugins.js]]
link = "plugins/youtube-lite.js"
lazy = true
