######################## Default configuration ####################
# The base URL of your site (required). For GitHub Pages project sites,
# include the repository name and a trailing slash.
baseURL = "https://polla-fattah.github.io/kailab/"
title = "Hugoplate"
theme = "hugoplate"

# Serve correct absolute/relative URLs when the site lives under /kailab/
canonifyURLs = true
relativeURLs = true

# Set your preferred time zone
timeZone = "Asia/Baghdad"

# Content language settings
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false
disableLanguages = []  # e.g., ["fr"] to disable French

# Post excerpt length
summaryLength = 10

############################# Services #############################
[services]

  [services.googleAnalytics]
  ID = "G-MEASUREMENT_ID"  # replace with your GA4 ID or leave empty

  [services.disqus]
  shortname = "themefisher-template"  # replace or remove if not used

############################ Permalinks ############################
# Correct table shape for permalinks. Map section names directly.
# Adjust section names ("pages", "posts", etc.) to match your content tree.
[permalinks]
pages = "/:slugorfilename/"

############################ Pagination ############################
[pagination]
disableAliases = false
pagerSize = 10
path = "page"

############################## Build ###############################
[build]

  [build.buildStats]
  enable = true

  # Cache-busting rule used by Hugoplate for the stats file
  [[build.cachebusters]]
  source = 'assets/notwatching/hugo_stats\.json'
  target = 'css'

############################# Modules ##############################
[module]
  # Mount the assets directory
  [[module.mounts]]
  source = "assets"
  target = "assets"

  # Mount the hugo_stats.json into a non-watched assets path
  [[module.mounts]]
  disableWatch = true
  source = "hugo_stats.json"
  target = "assets/notwatching/hugo_stats.json"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "WebAppManifest", "SearchIndex"]

############################# Imaging ##############################
[imaging]
# Default JPEG/WebP quality and resample filter
quality = 80
resampleFilter = "Lanczos"

############################# Caches ###############################
[caches]

  [caches.images]
  # Keep generated images inside the resourceDir for CI friendliness
  dir = ":resourceDir/_gen"
  maxAge = "720h"

  [caches.assets]
  dir = ":resourceDir/_gen"
  maxAge = "720h"

############################# Markup ###############################
[markup]

  [markup.goldmark.renderer]
  unsafe = true

  [markup.highlight]
  style = "monokai"     # see https://xyproto.github.io/splash/docs/all.html
  lineNumbersInTable = false

  [markup.tableOfContents]
  startLevel = 2
  endLevel = 5
  ordered = true

############################ Media types ###########################
[mediaTypes]
  [mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

########################### Output Formats #########################
[outputFormats]
  [outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

  [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

############################# Plugins ##############################
# Hugoplate expects these plugin assets to be available under /plugins and /js.
# With baseURL + canonifyURLs + relativeURLs, they will resolve correctly
# on GitHub Pages project sites.

# CSS Plugins
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
lazy = true

[[params.plugins.css]]
link = "plugins/glightbox/glightbox.css"
lazy = true

[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
lazy = true

[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
lazy = true

[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"
lazy = true

# JS Plugins
[[params.plugins.js]]
link = "js/search.js"
lazy = false

[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
lazy = false

[[params.plugins.js]]
link = "plugins/cookie.js"
lazy = false

[[params.plugins.js]]
link = "plugins/glightbox/glightbox.js"
lazy = true

[[params.plugins.js]]
link = "js/gallery-slider.js"
lazy = true

[[params.plugins.js]]
link = "js/accordion.js"
lazy = true

[[params.plugins.js]]
link = "js/tab.js"
lazy = true

[[params.plugins.js]]
link = "js/modal.js"
lazy = true

[[params.plugins.js]]
link = "plugins/youtube-lite.js"
lazy = true
