# workflow for building and deploying to GitHub Pages
name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

env:
  HUGO_ENVIRONMENT: production
  HUGO_VERSION: "0.147.3"
  GO_VERSION: "1.24.x"
  TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
  TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
  TINA_SEARCH_TOKEN: ${{ secrets.TINA_SEARCH_TOKEN }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install Hugo (extended)
        run: |
          wget -O ${{ runner.temp }}/hugo.deb \
            https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-arm64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Setup Node (Hugoplate needs Node 22+)
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Go (for Hugo Modules, per Hugoplate prereqs)
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      # Hugoplate's documented order: project-setup then install
      - name: Setup Project (Hugoplate)
        run: npm run project-setup

      - name: Install npm dependencies
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build site (Hugoplate)
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04-arm
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
